name = "Нигматиллаев Мохиржон"
description = "Менеджер по продажам коммерческой техники в компании VAN UNIVERSAL MOTORS"
keywords = ""
image = "IMG_1461.webp"
theme = "light"
primary_color = "#003b90"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = ""

[[sections]]
title = "Контакты"
description = ""
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = ""
[[sections.items]]
title = "Telegram"
description = "@VUMokhir"
url = "https://t.me/VUMokhir"
[[sections.items]]
title = "WhatsApp"
description = "+998941111840"
url = "https://wa.me/998941111840"
[[sections.items]]
title = "E-mail"
description = "monclermc@gmail.com"
url = "monclermc@gmail.com"


[[sections]]
title = "Ссылки"
description = "Социальные сети компании VUM"
direction = "row"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram"
title = "Instagram"
url = "https://www.instagram.com/vum_faw_uzbekistan"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube"
title = "YouTube"
url = "https://www.youtube.com/@faw_uzbekistan/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/google"
title = "Сайт"
url = "https://faw.uz"
[[sections.items]]
title = "Facebook"
icon = "https://cdn.simpleicons.org/facebook"
url = "https://www.facebook.com/fawuzbekistan"
